print('\033[0;33m====== DESAFIO 07 ======\033[m')
print('programa que calcula a media de 2 notas')
n1=float(input('digite a primeira nota: '))
n2=float(input('digite a segunda nota: '))
print('As notas digitadas foram: {} e {}. A media delas: {}'.format(n1,n2,(n1+n2)/2))
