print('\033[0;33m====== DESAFIO 04 ======\033[m')
n1 = input('Digite algo: ')
print('A variavel e do tipo', type(n1))
print('Voce digitou um numero: ' , n1.isnumeric())
print('Voce digitou um texto: ' , n1.isalpha())
print('Voce digitou um texto alfanumerico: ' , n1.isalnum())
print('Voce digitou um texto maiusculo: ' , n1.isupper())
print('Voce digitou um texto minusculo: ' , n1.islower())
print('Voce digitou um texto tem espacos: ' , n1.isspace())
print('Voce digitou um texto esta com as iniciais maiuscula: ' , n1.istitle())